# Generated by Django 4.1.1 on 2023-03-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.customer')),
                ('med_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.pharmacy')),
            ],
        ),
    ]
