# Generated by Django 4.1.1 on 2023-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
