# Generated by Django 4.1.1 on 2023-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
